/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AgendamentoConfirmadoRouteImport } from './routes/agendamento-confirmado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PainelSplatRouteImport } from './routes/painel.$'
import { Route as BMarkeeRouteImport } from './routes/b.markee'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AdminRecorrenciaRouteImport } from './routes/admin.recorrencia'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminMarkeeLeadsRouteImport } from './routes/admin.markee-leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as BMarkeeIndexRouteImport } from './routes/b.markee.index'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as AdminEmpresasIndexRouteImport } from './routes/admin.empresas.index'
import { Route as BMarkeeComecarRouteImport } from './routes/b.markee.comecar'
import { Route as BMarkeeAcompanhamentoRouteImport } from './routes/b.markee.acompanhamento'
import { Route as BSlugPainelRouteImport } from './routes/b.$slug.painel'
import { Route as BSlugMeusAgendamentosRouteImport } from './routes/b.$slug.meus-agendamentos'
import { Route as BSlugLoginRouteImport } from './routes/b.$slug.login'
import { Route as BSlugAgendarRouteImport } from './routes/b.$slug.agendar'
import { Route as BSlugAgendamentoConfirmadoRouteImport } from './routes/b.$slug.agendamento-confirmado'
import { Route as AdminEmpresasNovaRouteImport } from './routes/admin.empresas.nova'
import { Route as AdminEmpresasIdRouteImport } from './routes/admin.empresas.$id'
import { Route as BSlugPainelIndexRouteImport } from './routes/b.$slug.painel.index'
import { Route as BSlugPainelServicosRouteImport } from './routes/b.$slug.painel.servicos'
import { Route as BSlugPainelRecorrenciaRouteImport } from './routes/b.$slug.painel.recorrencia'
import { Route as BSlugPainelPagamentosRouteImport } from './routes/b.$slug.painel.pagamentos'
import { Route as BSlugPainelMaisAjustesRouteImport } from './routes/b.$slug.painel.mais-ajustes'
import { Route as BSlugPainelFluxoRouteImport } from './routes/b.$slug.painel.fluxo'
import { Route as BSlugPainelDisponibilidadeRouteImport } from './routes/b.$slug.painel.disponibilidade'
import { Route as BSlugPainelClientesRouteImport } from './routes/b.$slug.painel.clientes'
import { Route as BSlugPainelAvaliacoesRouteImport } from './routes/b.$slug.painel.avaliacoes'
import { Route as ApiPublicHooksWaFreeReminderTickRouteImport } from './routes/api/public/hooks/wa-free-reminder-tick'
import { Route as ApiPublicHooksRecurrenceTickRouteImport } from './routes/api/public/hooks/recurrence-tick'
import { Route as BSlugPainelServicosIndexRouteImport } from './routes/b.$slug.painel.servicos.index'
import { Route as BSlugPainelDisponibilidadeIndexRouteImport } from './routes/b.$slug.painel.disponibilidade.index'
import { Route as BSlugPainelServicosNovoRouteImport } from './routes/b.$slug.painel.servicos.novo'
import { Route as BSlugPainelServicosIdRouteImport } from './routes/b.$slug.painel.servicos.$id'
import { Route as BSlugPainelDisponibilidadeMaisAjustesRouteImport } from './routes/b.$slug.painel.disponibilidade.mais-ajustes'

const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoConfirmadoRoute = AgendamentoConfirmadoRouteImport.update({
  id: '/agendamento-confirmado',
  path: '/agendamento-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelSplatRoute = PainelSplatRouteImport.update({
  id: '/painel/$',
  path: '/painel/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BMarkeeRoute = BMarkeeRouteImport.update({
  id: '/b/markee',
  path: '/b/markee',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecorrenciaRoute = AdminRecorrenciaRouteImport.update({
  id: '/recorrencia',
  path: '/recorrencia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarkeeLeadsRoute = AdminMarkeeLeadsRouteImport.update({
  id: '/markee-leads',
  path: '/markee-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const BMarkeeIndexRoute = BMarkeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BMarkeeRoute,
} as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => AdminRoute,
} as any)
const BMarkeeComecarRoute = BMarkeeComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => BMarkeeRoute,
} as any)
const BMarkeeAcompanhamentoRoute = BMarkeeAcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => BMarkeeRoute,
} as any)
const BSlugPainelRoute = BSlugPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugMeusAgendamentosRoute = BSlugMeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugLoginRoute = BSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugAgendarRoute = BSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => BSlugRoute,
} as any)
const BSlugAgendamentoConfirmadoRoute =
  BSlugAgendamentoConfirmadoRouteImport.update({
    id: '/agendamento-confirmado',
    path: '/agendamento-confirmado',
    getParentRoute: () => BSlugRoute,
  } as any)
const AdminEmpresasNovaRoute = AdminEmpresasNovaRouteImport.update({
  id: '/empresas/nova',
  path: '/empresas/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasIdRoute = AdminEmpresasIdRouteImport.update({
  id: '/empresas/$id',
  path: '/empresas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const BSlugPainelIndexRoute = BSlugPainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelServicosRoute = BSlugPainelServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelRecorrenciaRoute = BSlugPainelRecorrenciaRouteImport.update({
  id: '/recorrencia',
  path: '/recorrencia',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelPagamentosRoute = BSlugPainelPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelMaisAjustesRoute = BSlugPainelMaisAjustesRouteImport.update({
  id: '/mais-ajustes',
  path: '/mais-ajustes',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelFluxoRoute = BSlugPainelFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelDisponibilidadeRoute =
  BSlugPainelDisponibilidadeRouteImport.update({
    id: '/disponibilidade',
    path: '/disponibilidade',
    getParentRoute: () => BSlugPainelRoute,
  } as any)
const BSlugPainelClientesRoute = BSlugPainelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const BSlugPainelAvaliacoesRoute = BSlugPainelAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => BSlugPainelRoute,
} as any)
const ApiPublicHooksWaFreeReminderTickRoute =
  ApiPublicHooksWaFreeReminderTickRouteImport.update({
    id: '/api/public/hooks/wa-free-reminder-tick',
    path: '/api/public/hooks/wa-free-reminder-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecurrenceTickRoute =
  ApiPublicHooksRecurrenceTickRouteImport.update({
    id: '/api/public/hooks/recurrence-tick',
    path: '/api/public/hooks/recurrence-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const BSlugPainelServicosIndexRoute =
  BSlugPainelServicosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BSlugPainelServicosRoute,
  } as any)
const BSlugPainelDisponibilidadeIndexRoute =
  BSlugPainelDisponibilidadeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BSlugPainelDisponibilidadeRoute,
  } as any)
const BSlugPainelServicosNovoRoute = BSlugPainelServicosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => BSlugPainelServicosRoute,
} as any)
const BSlugPainelServicosIdRoute = BSlugPainelServicosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BSlugPainelServicosRoute,
} as any)
const BSlugPainelDisponibilidadeMaisAjustesRoute =
  BSlugPainelDisponibilidadeMaisAjustesRouteImport.update({
    id: '/mais-ajustes',
    path: '/mais-ajustes',
    getParentRoute: () => BSlugPainelDisponibilidadeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento-confirmado': typeof AgendamentoConfirmadoRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markee-leads': typeof AdminMarkeeLeadsRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/recorrencia': typeof AdminRecorrenciaRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/b/markee': typeof BMarkeeRouteWithChildren
  '/painel/$': typeof PainelSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/b/$slug/agendamento-confirmado': typeof BSlugAgendamentoConfirmadoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/login': typeof BSlugLoginRoute
  '/b/$slug/meus-agendamentos': typeof BSlugMeusAgendamentosRoute
  '/b/$slug/painel': typeof BSlugPainelRouteWithChildren
  '/b/markee/acompanhamento': typeof BMarkeeAcompanhamentoRoute
  '/b/markee/comecar': typeof BMarkeeComecarRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/b/markee/': typeof BMarkeeIndexRoute
  '/api/public/hooks/recurrence-tick': typeof ApiPublicHooksRecurrenceTickRoute
  '/api/public/hooks/wa-free-reminder-tick': typeof ApiPublicHooksWaFreeReminderTickRoute
  '/b/$slug/painel/avaliacoes': typeof BSlugPainelAvaliacoesRoute
  '/b/$slug/painel/clientes': typeof BSlugPainelClientesRoute
  '/b/$slug/painel/disponibilidade': typeof BSlugPainelDisponibilidadeRouteWithChildren
  '/b/$slug/painel/fluxo': typeof BSlugPainelFluxoRoute
  '/b/$slug/painel/mais-ajustes': typeof BSlugPainelMaisAjustesRoute
  '/b/$slug/painel/pagamentos': typeof BSlugPainelPagamentosRoute
  '/b/$slug/painel/recorrencia': typeof BSlugPainelRecorrenciaRoute
  '/b/$slug/painel/servicos': typeof BSlugPainelServicosRouteWithChildren
  '/b/$slug/painel/': typeof BSlugPainelIndexRoute
  '/b/$slug/painel/disponibilidade/mais-ajustes': typeof BSlugPainelDisponibilidadeMaisAjustesRoute
  '/b/$slug/painel/servicos/$id': typeof BSlugPainelServicosIdRoute
  '/b/$slug/painel/servicos/novo': typeof BSlugPainelServicosNovoRoute
  '/b/$slug/painel/disponibilidade/': typeof BSlugPainelDisponibilidadeIndexRoute
  '/b/$slug/painel/servicos/': typeof BSlugPainelServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento-confirmado': typeof AgendamentoConfirmadoRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markee-leads': typeof AdminMarkeeLeadsRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/recorrencia': typeof AdminRecorrenciaRoute
  '/painel/$': typeof PainelSplatRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/b/$slug/agendamento-confirmado': typeof BSlugAgendamentoConfirmadoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/login': typeof BSlugLoginRoute
  '/b/$slug/meus-agendamentos': typeof BSlugMeusAgendamentosRoute
  '/b/markee/acompanhamento': typeof BMarkeeAcompanhamentoRoute
  '/b/markee/comecar': typeof BMarkeeComecarRoute
  '/admin/empresas': typeof AdminEmpresasIndexRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/b/markee': typeof BMarkeeIndexRoute
  '/api/public/hooks/recurrence-tick': typeof ApiPublicHooksRecurrenceTickRoute
  '/api/public/hooks/wa-free-reminder-tick': typeof ApiPublicHooksWaFreeReminderTickRoute
  '/b/$slug/painel/avaliacoes': typeof BSlugPainelAvaliacoesRoute
  '/b/$slug/painel/clientes': typeof BSlugPainelClientesRoute
  '/b/$slug/painel/fluxo': typeof BSlugPainelFluxoRoute
  '/b/$slug/painel/mais-ajustes': typeof BSlugPainelMaisAjustesRoute
  '/b/$slug/painel/pagamentos': typeof BSlugPainelPagamentosRoute
  '/b/$slug/painel/recorrencia': typeof BSlugPainelRecorrenciaRoute
  '/b/$slug/painel': typeof BSlugPainelIndexRoute
  '/b/$slug/painel/disponibilidade/mais-ajustes': typeof BSlugPainelDisponibilidadeMaisAjustesRoute
  '/b/$slug/painel/servicos/$id': typeof BSlugPainelServicosIdRoute
  '/b/$slug/painel/servicos/novo': typeof BSlugPainelServicosNovoRoute
  '/b/$slug/painel/disponibilidade': typeof BSlugPainelDisponibilidadeIndexRoute
  '/b/$slug/painel/servicos': typeof BSlugPainelServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendamento-confirmado': typeof AgendamentoConfirmadoRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markee-leads': typeof AdminMarkeeLeadsRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/recorrencia': typeof AdminRecorrenciaRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/b/markee': typeof BMarkeeRouteWithChildren
  '/painel/$': typeof PainelSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/empresas/$id': typeof AdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AdminEmpresasNovaRoute
  '/b/$slug/agendamento-confirmado': typeof BSlugAgendamentoConfirmadoRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/b/$slug/login': typeof BSlugLoginRoute
  '/b/$slug/meus-agendamentos': typeof BSlugMeusAgendamentosRoute
  '/b/$slug/painel': typeof BSlugPainelRouteWithChildren
  '/b/markee/acompanhamento': typeof BMarkeeAcompanhamentoRoute
  '/b/markee/comecar': typeof BMarkeeComecarRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/b/markee/': typeof BMarkeeIndexRoute
  '/api/public/hooks/recurrence-tick': typeof ApiPublicHooksRecurrenceTickRoute
  '/api/public/hooks/wa-free-reminder-tick': typeof ApiPublicHooksWaFreeReminderTickRoute
  '/b/$slug/painel/avaliacoes': typeof BSlugPainelAvaliacoesRoute
  '/b/$slug/painel/clientes': typeof BSlugPainelClientesRoute
  '/b/$slug/painel/disponibilidade': typeof BSlugPainelDisponibilidadeRouteWithChildren
  '/b/$slug/painel/fluxo': typeof BSlugPainelFluxoRoute
  '/b/$slug/painel/mais-ajustes': typeof BSlugPainelMaisAjustesRoute
  '/b/$slug/painel/pagamentos': typeof BSlugPainelPagamentosRoute
  '/b/$slug/painel/recorrencia': typeof BSlugPainelRecorrenciaRoute
  '/b/$slug/painel/servicos': typeof BSlugPainelServicosRouteWithChildren
  '/b/$slug/painel/': typeof BSlugPainelIndexRoute
  '/b/$slug/painel/disponibilidade/mais-ajustes': typeof BSlugPainelDisponibilidadeMaisAjustesRoute
  '/b/$slug/painel/servicos/$id': typeof BSlugPainelServicosIdRoute
  '/b/$slug/painel/servicos/novo': typeof BSlugPainelServicosNovoRoute
  '/b/$slug/painel/disponibilidade/': typeof BSlugPainelDisponibilidadeIndexRoute
  '/b/$slug/painel/servicos/': typeof BSlugPainelServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendamento-confirmado'
    | '/agendar'
    | '/login'
    | '/meus-agendamentos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/markee-leads'
    | '/admin/pagamentos'
    | '/admin/recorrencia'
    | '/b/$slug'
    | '/b/markee'
    | '/painel/$'
    | '/admin/'
    | '/painel/'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/b/$slug/agendamento-confirmado'
    | '/b/$slug/agendar'
    | '/b/$slug/login'
    | '/b/$slug/meus-agendamentos'
    | '/b/$slug/painel'
    | '/b/markee/acompanhamento'
    | '/b/markee/comecar'
    | '/admin/empresas/'
    | '/b/$slug/'
    | '/b/markee/'
    | '/api/public/hooks/recurrence-tick'
    | '/api/public/hooks/wa-free-reminder-tick'
    | '/b/$slug/painel/avaliacoes'
    | '/b/$slug/painel/clientes'
    | '/b/$slug/painel/disponibilidade'
    | '/b/$slug/painel/fluxo'
    | '/b/$slug/painel/mais-ajustes'
    | '/b/$slug/painel/pagamentos'
    | '/b/$slug/painel/recorrencia'
    | '/b/$slug/painel/servicos'
    | '/b/$slug/painel/'
    | '/b/$slug/painel/disponibilidade/mais-ajustes'
    | '/b/$slug/painel/servicos/$id'
    | '/b/$slug/painel/servicos/novo'
    | '/b/$slug/painel/disponibilidade/'
    | '/b/$slug/painel/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento-confirmado'
    | '/agendar'
    | '/login'
    | '/meus-agendamentos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/markee-leads'
    | '/admin/pagamentos'
    | '/admin/recorrencia'
    | '/painel/$'
    | '/admin'
    | '/painel'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/b/$slug/agendamento-confirmado'
    | '/b/$slug/agendar'
    | '/b/$slug/login'
    | '/b/$slug/meus-agendamentos'
    | '/b/markee/acompanhamento'
    | '/b/markee/comecar'
    | '/admin/empresas'
    | '/b/$slug'
    | '/b/markee'
    | '/api/public/hooks/recurrence-tick'
    | '/api/public/hooks/wa-free-reminder-tick'
    | '/b/$slug/painel/avaliacoes'
    | '/b/$slug/painel/clientes'
    | '/b/$slug/painel/fluxo'
    | '/b/$slug/painel/mais-ajustes'
    | '/b/$slug/painel/pagamentos'
    | '/b/$slug/painel/recorrencia'
    | '/b/$slug/painel'
    | '/b/$slug/painel/disponibilidade/mais-ajustes'
    | '/b/$slug/painel/servicos/$id'
    | '/b/$slug/painel/servicos/novo'
    | '/b/$slug/painel/disponibilidade'
    | '/b/$slug/painel/servicos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendamento-confirmado'
    | '/agendar'
    | '/login'
    | '/meus-agendamentos'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/markee-leads'
    | '/admin/pagamentos'
    | '/admin/recorrencia'
    | '/b/$slug'
    | '/b/markee'
    | '/painel/$'
    | '/admin/'
    | '/painel/'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/b/$slug/agendamento-confirmado'
    | '/b/$slug/agendar'
    | '/b/$slug/login'
    | '/b/$slug/meus-agendamentos'
    | '/b/$slug/painel'
    | '/b/markee/acompanhamento'
    | '/b/markee/comecar'
    | '/admin/empresas/'
    | '/b/$slug/'
    | '/b/markee/'
    | '/api/public/hooks/recurrence-tick'
    | '/api/public/hooks/wa-free-reminder-tick'
    | '/b/$slug/painel/avaliacoes'
    | '/b/$slug/painel/clientes'
    | '/b/$slug/painel/disponibilidade'
    | '/b/$slug/painel/fluxo'
    | '/b/$slug/painel/mais-ajustes'
    | '/b/$slug/painel/pagamentos'
    | '/b/$slug/painel/recorrencia'
    | '/b/$slug/painel/servicos'
    | '/b/$slug/painel/'
    | '/b/$slug/painel/disponibilidade/mais-ajustes'
    | '/b/$slug/painel/servicos/$id'
    | '/b/$slug/painel/servicos/novo'
    | '/b/$slug/painel/disponibilidade/'
    | '/b/$slug/painel/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendamentoConfirmadoRoute: typeof AgendamentoConfirmadoRoute
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  BMarkeeRoute: typeof BMarkeeRouteWithChildren
  PainelSplatRoute: typeof PainelSplatRoute
  PainelIndexRoute: typeof PainelIndexRoute
  ApiPublicHooksRecurrenceTickRoute: typeof ApiPublicHooksRecurrenceTickRoute
  ApiPublicHooksWaFreeReminderTickRoute: typeof ApiPublicHooksWaFreeReminderTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento-confirmado': {
      id: '/agendamento-confirmado'
      path: '/agendamento-confirmado'
      fullPath: '/agendamento-confirmado'
      preLoaderRoute: typeof AgendamentoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/$': {
      id: '/painel/$'
      path: '/painel/$'
      fullPath: '/painel/$'
      preLoaderRoute: typeof PainelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/markee': {
      id: '/b/markee'
      path: '/b/markee'
      fullPath: '/b/markee'
      preLoaderRoute: typeof BMarkeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recorrencia': {
      id: '/admin/recorrencia'
      path: '/recorrencia'
      fullPath: '/admin/recorrencia'
      preLoaderRoute: typeof AdminRecorrenciaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markee-leads': {
      id: '/admin/markee-leads'
      path: '/markee-leads'
      fullPath: '/admin/markee-leads'
      preLoaderRoute: typeof AdminMarkeeLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/b/markee/': {
      id: '/b/markee/'
      path: '/'
      fullPath: '/b/markee/'
      preLoaderRoute: typeof BMarkeeIndexRouteImport
      parentRoute: typeof BMarkeeRoute
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/admin/empresas/': {
      id: '/admin/empresas/'
      path: '/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/b/markee/comecar': {
      id: '/b/markee/comecar'
      path: '/comecar'
      fullPath: '/b/markee/comecar'
      preLoaderRoute: typeof BMarkeeComecarRouteImport
      parentRoute: typeof BMarkeeRoute
    }
    '/b/markee/acompanhamento': {
      id: '/b/markee/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/b/markee/acompanhamento'
      preLoaderRoute: typeof BMarkeeAcompanhamentoRouteImport
      parentRoute: typeof BMarkeeRoute
    }
    '/b/$slug/painel': {
      id: '/b/$slug/painel'
      path: '/painel'
      fullPath: '/b/$slug/painel'
      preLoaderRoute: typeof BSlugPainelRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/meus-agendamentos': {
      id: '/b/$slug/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/b/$slug/meus-agendamentos'
      preLoaderRoute: typeof BSlugMeusAgendamentosRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/login': {
      id: '/b/$slug/login'
      path: '/login'
      fullPath: '/b/$slug/login'
      preLoaderRoute: typeof BSlugLoginRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/agendar': {
      id: '/b/$slug/agendar'
      path: '/agendar'
      fullPath: '/b/$slug/agendar'
      preLoaderRoute: typeof BSlugAgendarRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/b/$slug/agendamento-confirmado': {
      id: '/b/$slug/agendamento-confirmado'
      path: '/agendamento-confirmado'
      fullPath: '/b/$slug/agendamento-confirmado'
      preLoaderRoute: typeof BSlugAgendamentoConfirmadoRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/admin/empresas/nova': {
      id: '/admin/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/admin/empresas/nova'
      preLoaderRoute: typeof AdminEmpresasNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas/$id': {
      id: '/admin/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/admin/empresas/$id'
      preLoaderRoute: typeof AdminEmpresasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/b/$slug/painel/': {
      id: '/b/$slug/painel/'
      path: '/'
      fullPath: '/b/$slug/painel/'
      preLoaderRoute: typeof BSlugPainelIndexRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/servicos': {
      id: '/b/$slug/painel/servicos'
      path: '/servicos'
      fullPath: '/b/$slug/painel/servicos'
      preLoaderRoute: typeof BSlugPainelServicosRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/recorrencia': {
      id: '/b/$slug/painel/recorrencia'
      path: '/recorrencia'
      fullPath: '/b/$slug/painel/recorrencia'
      preLoaderRoute: typeof BSlugPainelRecorrenciaRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/pagamentos': {
      id: '/b/$slug/painel/pagamentos'
      path: '/pagamentos'
      fullPath: '/b/$slug/painel/pagamentos'
      preLoaderRoute: typeof BSlugPainelPagamentosRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/mais-ajustes': {
      id: '/b/$slug/painel/mais-ajustes'
      path: '/mais-ajustes'
      fullPath: '/b/$slug/painel/mais-ajustes'
      preLoaderRoute: typeof BSlugPainelMaisAjustesRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/fluxo': {
      id: '/b/$slug/painel/fluxo'
      path: '/fluxo'
      fullPath: '/b/$slug/painel/fluxo'
      preLoaderRoute: typeof BSlugPainelFluxoRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/disponibilidade': {
      id: '/b/$slug/painel/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/b/$slug/painel/disponibilidade'
      preLoaderRoute: typeof BSlugPainelDisponibilidadeRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/clientes': {
      id: '/b/$slug/painel/clientes'
      path: '/clientes'
      fullPath: '/b/$slug/painel/clientes'
      preLoaderRoute: typeof BSlugPainelClientesRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/b/$slug/painel/avaliacoes': {
      id: '/b/$slug/painel/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/b/$slug/painel/avaliacoes'
      preLoaderRoute: typeof BSlugPainelAvaliacoesRouteImport
      parentRoute: typeof BSlugPainelRoute
    }
    '/api/public/hooks/wa-free-reminder-tick': {
      id: '/api/public/hooks/wa-free-reminder-tick'
      path: '/api/public/hooks/wa-free-reminder-tick'
      fullPath: '/api/public/hooks/wa-free-reminder-tick'
      preLoaderRoute: typeof ApiPublicHooksWaFreeReminderTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recurrence-tick': {
      id: '/api/public/hooks/recurrence-tick'
      path: '/api/public/hooks/recurrence-tick'
      fullPath: '/api/public/hooks/recurrence-tick'
      preLoaderRoute: typeof ApiPublicHooksRecurrenceTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/painel/servicos/': {
      id: '/b/$slug/painel/servicos/'
      path: '/'
      fullPath: '/b/$slug/painel/servicos/'
      preLoaderRoute: typeof BSlugPainelServicosIndexRouteImport
      parentRoute: typeof BSlugPainelServicosRoute
    }
    '/b/$slug/painel/disponibilidade/': {
      id: '/b/$slug/painel/disponibilidade/'
      path: '/'
      fullPath: '/b/$slug/painel/disponibilidade/'
      preLoaderRoute: typeof BSlugPainelDisponibilidadeIndexRouteImport
      parentRoute: typeof BSlugPainelDisponibilidadeRoute
    }
    '/b/$slug/painel/servicos/novo': {
      id: '/b/$slug/painel/servicos/novo'
      path: '/novo'
      fullPath: '/b/$slug/painel/servicos/novo'
      preLoaderRoute: typeof BSlugPainelServicosNovoRouteImport
      parentRoute: typeof BSlugPainelServicosRoute
    }
    '/b/$slug/painel/servicos/$id': {
      id: '/b/$slug/painel/servicos/$id'
      path: '/$id'
      fullPath: '/b/$slug/painel/servicos/$id'
      preLoaderRoute: typeof BSlugPainelServicosIdRouteImport
      parentRoute: typeof BSlugPainelServicosRoute
    }
    '/b/$slug/painel/disponibilidade/mais-ajustes': {
      id: '/b/$slug/painel/disponibilidade/mais-ajustes'
      path: '/mais-ajustes'
      fullPath: '/b/$slug/painel/disponibilidade/mais-ajustes'
      preLoaderRoute: typeof BSlugPainelDisponibilidadeMaisAjustesRouteImport
      parentRoute: typeof BSlugPainelDisponibilidadeRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarkeeLeadsRoute: typeof AdminMarkeeLeadsRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminRecorrenciaRoute: typeof AdminRecorrenciaRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmpresasIdRoute: typeof AdminEmpresasIdRoute
  AdminEmpresasNovaRoute: typeof AdminEmpresasNovaRoute
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarkeeLeadsRoute: AdminMarkeeLeadsRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminRecorrenciaRoute: AdminRecorrenciaRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmpresasIdRoute: AdminEmpresasIdRoute,
  AdminEmpresasNovaRoute: AdminEmpresasNovaRoute,
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BSlugPainelDisponibilidadeRouteChildren {
  BSlugPainelDisponibilidadeMaisAjustesRoute: typeof BSlugPainelDisponibilidadeMaisAjustesRoute
  BSlugPainelDisponibilidadeIndexRoute: typeof BSlugPainelDisponibilidadeIndexRoute
}

const BSlugPainelDisponibilidadeRouteChildren: BSlugPainelDisponibilidadeRouteChildren =
  {
    BSlugPainelDisponibilidadeMaisAjustesRoute:
      BSlugPainelDisponibilidadeMaisAjustesRoute,
    BSlugPainelDisponibilidadeIndexRoute: BSlugPainelDisponibilidadeIndexRoute,
  }

const BSlugPainelDisponibilidadeRouteWithChildren =
  BSlugPainelDisponibilidadeRoute._addFileChildren(
    BSlugPainelDisponibilidadeRouteChildren,
  )

interface BSlugPainelServicosRouteChildren {
  BSlugPainelServicosIdRoute: typeof BSlugPainelServicosIdRoute
  BSlugPainelServicosNovoRoute: typeof BSlugPainelServicosNovoRoute
  BSlugPainelServicosIndexRoute: typeof BSlugPainelServicosIndexRoute
}

const BSlugPainelServicosRouteChildren: BSlugPainelServicosRouteChildren = {
  BSlugPainelServicosIdRoute: BSlugPainelServicosIdRoute,
  BSlugPainelServicosNovoRoute: BSlugPainelServicosNovoRoute,
  BSlugPainelServicosIndexRoute: BSlugPainelServicosIndexRoute,
}

const BSlugPainelServicosRouteWithChildren =
  BSlugPainelServicosRoute._addFileChildren(BSlugPainelServicosRouteChildren)

interface BSlugPainelRouteChildren {
  BSlugPainelAvaliacoesRoute: typeof BSlugPainelAvaliacoesRoute
  BSlugPainelClientesRoute: typeof BSlugPainelClientesRoute
  BSlugPainelDisponibilidadeRoute: typeof BSlugPainelDisponibilidadeRouteWithChildren
  BSlugPainelFluxoRoute: typeof BSlugPainelFluxoRoute
  BSlugPainelMaisAjustesRoute: typeof BSlugPainelMaisAjustesRoute
  BSlugPainelPagamentosRoute: typeof BSlugPainelPagamentosRoute
  BSlugPainelRecorrenciaRoute: typeof BSlugPainelRecorrenciaRoute
  BSlugPainelServicosRoute: typeof BSlugPainelServicosRouteWithChildren
  BSlugPainelIndexRoute: typeof BSlugPainelIndexRoute
}

const BSlugPainelRouteChildren: BSlugPainelRouteChildren = {
  BSlugPainelAvaliacoesRoute: BSlugPainelAvaliacoesRoute,
  BSlugPainelClientesRoute: BSlugPainelClientesRoute,
  BSlugPainelDisponibilidadeRoute: BSlugPainelDisponibilidadeRouteWithChildren,
  BSlugPainelFluxoRoute: BSlugPainelFluxoRoute,
  BSlugPainelMaisAjustesRoute: BSlugPainelMaisAjustesRoute,
  BSlugPainelPagamentosRoute: BSlugPainelPagamentosRoute,
  BSlugPainelRecorrenciaRoute: BSlugPainelRecorrenciaRoute,
  BSlugPainelServicosRoute: BSlugPainelServicosRouteWithChildren,
  BSlugPainelIndexRoute: BSlugPainelIndexRoute,
}

const BSlugPainelRouteWithChildren = BSlugPainelRoute._addFileChildren(
  BSlugPainelRouteChildren,
)

interface BSlugRouteChildren {
  BSlugAgendamentoConfirmadoRoute: typeof BSlugAgendamentoConfirmadoRoute
  BSlugAgendarRoute: typeof BSlugAgendarRoute
  BSlugLoginRoute: typeof BSlugLoginRoute
  BSlugMeusAgendamentosRoute: typeof BSlugMeusAgendamentosRoute
  BSlugPainelRoute: typeof BSlugPainelRouteWithChildren
  BSlugIndexRoute: typeof BSlugIndexRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugAgendamentoConfirmadoRoute: BSlugAgendamentoConfirmadoRoute,
  BSlugAgendarRoute: BSlugAgendarRoute,
  BSlugLoginRoute: BSlugLoginRoute,
  BSlugMeusAgendamentosRoute: BSlugMeusAgendamentosRoute,
  BSlugPainelRoute: BSlugPainelRouteWithChildren,
  BSlugIndexRoute: BSlugIndexRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

interface BMarkeeRouteChildren {
  BMarkeeAcompanhamentoRoute: typeof BMarkeeAcompanhamentoRoute
  BMarkeeComecarRoute: typeof BMarkeeComecarRoute
  BMarkeeIndexRoute: typeof BMarkeeIndexRoute
}

const BMarkeeRouteChildren: BMarkeeRouteChildren = {
  BMarkeeAcompanhamentoRoute: BMarkeeAcompanhamentoRoute,
  BMarkeeComecarRoute: BMarkeeComecarRoute,
  BMarkeeIndexRoute: BMarkeeIndexRoute,
}

const BMarkeeRouteWithChildren =
  BMarkeeRoute._addFileChildren(BMarkeeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendamentoConfirmadoRoute: AgendamentoConfirmadoRoute,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  BSlugRoute: BSlugRouteWithChildren,
  BMarkeeRoute: BMarkeeRouteWithChildren,
  PainelSplatRoute: PainelSplatRoute,
  PainelIndexRoute: PainelIndexRoute,
  ApiPublicHooksRecurrenceTickRoute: ApiPublicHooksRecurrenceTickRoute,
  ApiPublicHooksWaFreeReminderTickRoute: ApiPublicHooksWaFreeReminderTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
