// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfoasidbhvysldtnihhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb2FzaWRiaHZ5c2xkdG5paGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwMjQ4NDEsImV4cCI6MjA5NTYwMDg0MX0.HhrQPQmwUJEpS2vMq6yCDHM1t3UHIzBhlIF8OLnQJgU";
const supabaseStorage = typeof window !== "undefined" ? window.localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: supabaseStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});